### ISSUE TITLE
Chromium Alpha - Status Bar, Downloads Button, and so on

### ISSUE THREAD

**Issue by dominichayesferen** [angelbruni/Geckium#129]
That Linux Dude Dominic Hayes thatlinuxdude
 — 08/06/2024 00:31

![image](https://github.com/user-attachments/assets/69ecaea8-e6a0-451b-8e58-cbc7fd9d3370)

**Comment by PF94** [comment]
im pretty sure this is just firefox 2.x/3.x with a chrome theme.

the original uncompressed screenshot is https://www.flickr.com/photos/ymbiont/2965991658/, it was published after the release of chrome 0.2, i did some digging and found the author's linkedin. if this screenshot was of a pre-0.2 build of chrome/chromium. they would've worked at google. despite this, there is nothing on their linkedin about them working at google in 2008.

![image](https://github.com/user-attachments/assets/dada1414-7161-474a-9203-ed95c9d65d18)

(https://web.archive.org/web/20130829061131/https://www.linkedin.com/in/ceedub)

theres an icon for firebug in the status bar which was an extension for firefox back then.

heres a screenshot of a very early build of firefox 3.6 that i took from http://www.kylescholz.com/blog/2008/11/digging_into_paint_events_in_f_1.html because im too lazy to set up a throwaway install of old late-2000s firefox

![firebugpaintevents](https://github.com/user-attachments/assets/d5b2988b-82e0-47d3-8e71-8f1a87aba588)

notice how the firebug icon perfectly matches with the one in the supposed "chromium alpha" screenshot

![paintdotnet_r4LQib1pU5](https://github.com/user-attachments/assets/84800331-cc79-45a5-9c80-8ae459e05ee4)

**Comment by dominichayesferen** [comment]
Well dang ain't that ironic.

Caught by a coincidence - if you've seen Linux Chromium Alpha, you'll know why it's so coincidental.

**Comment by dominichayesferen** [comment]
![image](https://github.com/user-attachments/assets/bad8157d-4fdd-4538-a0e9-12ca929f3c7c)


> Well dang ain't that ironic.
> 
> Caught by a coincidence - if you've seen Linux Chromium Alpha, you'll know why it's so uncannily coincidental.

**Comment by angelbruni** [comment]
> Well dang ain't that ironic.
> 
> Caught by a coincidence - if you've seen Linux Chromium Alpha, you'll know why it's so uncannily coincidental.

I knew it.
Can't believe I never noticed the Firebug icon but noticed the favourites icon being similar to Firefox's...
If you remember, you remember.
