### ISSUE TITLE
Add instructions for Linux using systemd-sysext

### ISSUE THREAD

**Issue by AyeItsHarry** [angelbruni/Geckium#321]
### Before sending your suggestion

- [X] My version of Firefox is up to date (for 115, this means being on at least 115.16.1)
- [X] My copy of Geckium is up to date (no update option in the hamburger/spanner menu)

### What browser are you running Geckium on?

Mozilla Firefox

### What Operating System are you running Geckium on?

Fedora Kinoite 41

### What would you like to suggest for Geckium?

With the current Linux installation instructions, lib files are directly modified, which is not ideal for many reasons - mainly those of us who use immutable distros. Instead, by creating a layer with systemd-sysext which is added on top of the /usr directory, lib files are not directly modified, preventing potential conflicts. Additionally, it allows Geckium to work with immutable distros like Fedora Silverblue.

### Additional Context

```
/var/lib/extensions/geckium/
└── usr
    ├── lib
    │   └── extension-release.d
    │       └── extension-release.geckium
    └── lib64
        └── firefox
            ├── config.js
            └── defaults
                └── pref
                    └── config-prefs.js
```
After setting up a file hierarchy as so (for the extension release, run `cp /etc/os-release /var/lib/extensions/geckium/usr/lib/extension-release.d/extension-release.geckium`), the extension can be layered by running:
```
# systemd-sysext merge
```
It can also be enabled to run at startup with the following command:
```
# systemctl enable systemd-sysext
```

**Comment by angelbruni** [comment]
This is interesting, I personally have 0 experience with immutable distros

**Comment by dominichayesferen** [comment]
This is by far TOO niche right now for a project like Geckium which is made for casual users.

If you're using an immutable distribution:
- You likely already know about how to do this anyways, because you went out of your way to install Firefox in the required way for this
- Otherwise you're using Firefox from Distrobox, which this isn't appropriate for
- This assumes your immutable OS is one powered by systemd immutability technologies - this therefore doesn't apply to other immutable distros, including Vanilla OS, Steam OS(?), and potentially soon GNOME OS too iirc

There just isn't a place for this in the main guide right now due to all of these factors (whereas the non-immutable method is a generic way for all non-immutables), but maybe it could have a place on the Wiki... assuming there's a note about the exclusivity of this method to those specific immutable distributions.
