### ISSUE TITLE
Ability to disable download shelf

### ISSUE THREAD

**Issue by Zer0PXL** [angelbruni/Geckium#344]
### Before sending your suggestion

- [X] My version of Firefox is up to date (for 115, this means being on at least 115.16.1)
- [X] My copy of Geckium is up to date (no update option in the hamburger/spanner menu)

### What browser are you running Geckium on?

Mozilla Firefox

### What Operating System are you running Geckium on?

Windows 10

### What would you like to suggest for Geckium?

I just want a toggle to disable the download shelf since I find Firefox's download menu more intuitive.

**Comment by angelbruni** [comment]
You can disable it by going to Menubar -> Tools -> userScripts -> Geckium_downloadManager.uc.js
Then Menubar -> Tools -> userScripts -> Clear startup cache and Restart Firefox 

This is an UNOFFICIAL METHOD, when a toggle is added to Geckium Settings, TURN IT BACK ON and disable in there instead.

Leaving the issue here so I don't forget to make a toggle for it.

**Comment by angelbruni** [comment]
Setting added in commit https://github.com/angelbruni/Geckium/commit/ba9821a982e6d8016e934e3cf21e7fc4eb58c703.
I will close this issue when I release the update as I feel like it's important to inform directly that a released update contains this as an implemented feature rather than letting the user discover that, especially since I will have to inform users that they have to re-enable the `Geckium_downloadManager.uc.js` script again when said update is finally released.

**Comment by angelbruni** [comment]
Setting added in the update https://github.com/angelbruni/Geckium/releases/tag/b0.20.11.
